
package com.rollingstone.recipes.oxm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RecipePort", targetNamespace = "http://binit.blogspot.com/ws/schema/recipe")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecipePort {


    /**
     * 
     * @param editRecipeRequest
     * @return
     *     returns com.rollingstone.recipes.oxm.EditRecipeResponse
     */
    @WebMethod
    @WebResult(name = "editRecipeResponse", targetNamespace = "http://binit.blogspot.com/ws/schema/recipe", partName = "editRecipeResponse")
    public EditRecipeResponse editRecipe(
        @WebParam(name = "editRecipeRequest", targetNamespace = "http://binit.blogspot.com/ws/schema/recipe", partName = "editRecipeRequest")
        EditRecipeRequest editRecipeRequest);

    /**
     * 
     * @param getRecipeRequest
     * @return
     *     returns com.rollingstone.recipes.oxm.GetRecipeResponse
     */
    @WebMethod
    @WebResult(name = "getRecipeResponse", targetNamespace = "http://binit.blogspot.com/ws/schema/recipe", partName = "getRecipeResponse")
    public GetRecipeResponse getRecipe(
        @WebParam(name = "getRecipeRequest", targetNamespace = "http://binit.blogspot.com/ws/schema/recipe", partName = "getRecipeRequest")
        GetRecipeRequest getRecipeRequest);

    /**
     * 
     * @param deleteRecipeRequest
     * @return
     *     returns com.rollingstone.recipes.oxm.DeleteRecipeResponse
     */
    @WebMethod
    @WebResult(name = "deleteRecipeResponse", targetNamespace = "http://binit.blogspot.com/ws/schema/recipe", partName = "deleteRecipeResponse")
    public DeleteRecipeResponse deleteRecipe(
        @WebParam(name = "deleteRecipeRequest", targetNamespace = "http://binit.blogspot.com/ws/schema/recipe", partName = "deleteRecipeRequest")
        DeleteRecipeRequest deleteRecipeRequest);

}
