
package com.rollingstone.recipes.oxm;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RecipePortService", targetNamespace = "http://binit.blogspot.com/ws/schema/recipe", wsdlLocation = "http://localhost:8080/spring-ws-recipe/binit/ws/recipe.wsdl")
public class RecipePortService
    extends Service
{

    private final static URL RECIPEPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rollingstone.recipes.oxm.RecipePortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rollingstone.recipes.oxm.RecipePortService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/spring-ws-recipe/binit/ws/recipe.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/spring-ws-recipe/binit/ws/recipe.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RECIPEPORTSERVICE_WSDL_LOCATION = url;
    }

    public RecipePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecipePortService() {
        super(RECIPEPORTSERVICE_WSDL_LOCATION, new QName("http://binit.blogspot.com/ws/schema/recipe", "RecipePortService"));
    }

    /**
     * 
     * @return
     *     returns RecipePort
     */
    @WebEndpoint(name = "RecipePortSoap11")
    public RecipePort getRecipePortSoap11() {
        return super.getPort(new QName("http://binit.blogspot.com/ws/schema/recipe", "RecipePortSoap11"), RecipePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecipePort
     */
    @WebEndpoint(name = "RecipePortSoap11")
    public RecipePort getRecipePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://binit.blogspot.com/ws/schema/recipe", "RecipePortSoap11"), RecipePort.class, features);
    }

}
