DROP TABLE IF EXISTS `RECIPE`;
CREATE TABLE `RECIPE` (
  `RECIPEID` int(11) NOT NULL AUTO_INCREMENT,
  `RECIPE_NAME` varchar(200) DEFAULT NULL,
  `DESCRIPTION` varchar(2000) DEFAULT NULL,
  `CREATED_ON` date DEFAULT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `RECIPETYPE` varchar(200) DEFAULT NULL,
  `VISITOR_COUNT` int(11) DEFAULT NULL,
  `PROCESS` text,
  PRIMARY KEY (`RECIPEID`)
);

DROP TABLE IF EXISTS `RECIPE_INGREDIENTS`;
CREATE TABLE `RECIPE_INGREDIENTS` (
  `INGREDIENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INGREDIENT_NAME` varchar(200) DEFAULT NULL,
  `UOM` varchar(200) DEFAULT NULL,
  `QUANTITY` varchar(200) DEFAULT NULL,
  `RECIPEID` int(11) DEFAULT NULL,
  PRIMARY KEY (`INGREDIENT_ID`)
);

-- For reference. You can insert data from UI.
INSERT INTO `test`.`RECIPE` (`RECIPE_NAME`, `DESCRIPTION`, `CREATED_ON`, `CREATED_BY`, `RECIPETYPE`, `VISITOR_COUNT`, `PROCESS`) 
VALUES ('Test1', 'Test', '2013-04-01', 'Admin', 'American', '23', 'xyz');
INSERT INTO `test`.`RECIPE` (`RECIPE_NAME`, `DESCRIPTION`, `CREATED_ON`, `CREATED_BY`, `RECIPETYPE`, `VISITOR_COUNT`, `PROCESS`) 
VALUES ('Test2', 'Test', '2013-05-11', 'Admin', 'American', '23', 'xyz');
INSERT INTO `test`.`RECIPE` (`RECIPE_NAME`, `DESCRIPTION`, `CREATED_ON`, `CREATED_BY`, `RECIPETYPE`, `VISITOR_COUNT`, `PROCESS`) 
VALUES ('Test3', 'Test', '2013-05-31', 'Admin', 'American', '23', 'xyz');
INSERT INTO `test`.`RECIPE` (`RECIPE_NAME`, `DESCRIPTION`, `CREATED_ON`, `CREATED_BY`, `RECIPETYPE`, `VISITOR_COUNT`, `PROCESS`) 
VALUES ('Test4', 'Test', '2013-02-01', 'Admin', 'American', '23', 'xyz');


INSERT INTO `test`.`RECIPE_INGREDIENTS` (`INGREDIENT_NAME`, `UOM`, `QUANTITY`, `RECIPEID`) VALUES ('Salt', 'bla bla', '100gm', '1');
INSERT INTO `test`.`RECIPE_INGREDIENTS` (`INGREDIENT_NAME`, `UOM`, `QUANTITY`, `RECIPEID`) VALUES ('Sugar', '323', '200gm', '1');
INSERT INTO `test`.`RECIPE_INGREDIENTS` (`INGREDIENT_NAME`, `UOM`, `QUANTITY`, `RECIPEID`) VALUES ('Chicken', '342', '1kg', '1');
INSERT INTO `test`.`RECIPE_INGREDIENTS` (`INGREDIENT_NAME`, `UOM`, `QUANTITY`, `RECIPEID`) VALUES ('Mutton', '4dfgdf', '1kg', '2');
INSERT INTO `test`.`RECIPE_INGREDIENTS` (`INGREDIENT_NAME`, `UOM`, `QUANTITY`, `RECIPEID`) VALUES ('Veg', 'dff', '300gm', '3');
